Use rust stable alpine image instead of nightly
Fix "error[E0635]: unknown feature `proc_macro_span_shrink`" in
latest build. Also see https://substrate.stackexchange.com/a/9069.