Downgrade Alpine to 3.12 for rsync
rsync v3.2.4 - 3.2.5 contains a grievous bug which breaks all rsync mirrors:

/ # apk add rsync && rsync -r rsync.trisquel.info::trisquel.packages /tmp
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/5) Installing libacl (2.3.1-r0)
(2/5) Installing lz4-libs (1.9.3-r1)
(3/5) Installing popt (1.18-r0)
(4/5) Installing zstd-libs (1.5.2-r1)
(5/5) Installing rsync (3.2.4-r2)
Executing busybox-1.35.0-r17.trigger
OK: 7 MiB in 19 packages
ERROR: rejecting unrequested file-list name: meta-release-development
rsync error: protocol incompatibility (code 2) at flist.c(998) [Receiver=3.2.4]

this bug got fixed in rsync v3.2.6, but let's just wait it to be in stable Alpine.